#define MATRIX_ROW_PINS_RIGHT {D5, C6, D4, D0}
#define MATRIX_COL_PINS_RIGHT {F1, F5, B1, F6, B2}

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

#define BOOTMAGIC_ROW_RIGHT 4
#define BOOTMAGIC_COLUMN_RIGHT 0

#define SPLIT_HAND_PIN B7
#define SPLIT_HAND_PIN_LOW_IS_LEFT

#define SOFT_SERIAL_PIN D3

#define MATRIX_ROW_PINS_RIGHT {D5, C6, D4, D0}
#define MATRIX_COL_PINS_RIGHT {F1, F5, B1, F6, B2}

#define BOOTMAGIC_ROW 0
#define BOOTMAGIC_COLUMN 0

#define BOOTMAGIC_ROW_RIGHT 4
#define BOOTMAGIC_COLUMN_RIGHT 0

#define SPLIT_HAND_PIN B7
#define SPLIT_HAND_PIN_LOW_IS_LEFT

#define SOFT_SERIAL_PIN D3
